### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools.command.bdist_wheel'

### ISSUE THREAD

**Issue by meme-lord** [ydkhatri/pyliblzfse#4]
I was getting this error when trying to install

```
$ pip install pyliblzfse --break-system-packages
Collecting pyliblzfse
  Using cached pyliblzfse-0.4.1.tar.gz (47 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyliblzfse
  Building wheel for pyliblzfse (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5da03vru/pyliblzfse_c4a06383729b4c95986a377f77917360/setup.py", line 40, in <module>
          setup(name='pyliblzfse',
        File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 171, in setup
          ok = dist.parse_command_line()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 476, in parse_command_line
          args = self._parse_command_opts(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 869, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 535, in _parse_command_opts
          cmd_class = self.get_command_class(command)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 714, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
                                              ^^^^^^^^^
        File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
          module = import_module(match.group('module'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'setuptools.command.bdist_wheel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyliblzfse
  Running setup.py clean for pyliblzfse
Failed to build pyliblzfse
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyliblzfse)
```

Solution was:
```sh
python -m pip install --use-pep517 pyliblzfse --break-system-packages
```

Perhaps a pyproject.toml file could be added to avoid this issue

**Comment by ydkhatri-cybercx** [comment]
With python 3.12, I believe you'll also need to install and upgrade setuptools, as it may not be there by default.
```
pip install setuptools --upgrade
```

**Comment by ydkhatri** [comment]
I cannot reproduce this issue. What version of OS are you on?
